### ISSUE TITLE
AQI and PM2.5 values to icon capabilities seem swapped

### ISSUE THREAD

**Issue by kgiori** [tim-hellhake/purpleair-adapter#2]
Expected:
Air Quality Sensor capability => AQI value
Multi Level Sensor capability => PM2.5 value

When in "Edit" mode of the Thing icon, selecting Air Quality results in the main icon showing the PM2.5 value (as an int).
When selecting "Multi Level Sensor", it instead shows the AQI value. I think they should be swapped?

**Comment by tim-hellhake** [comment]
I think that should be fine.
According to the schema the [AirQualitySensor](https://iot.mozilla.org/schemas/#AirQualitySensor) has a [DensityProperty](https://iot.mozilla.org/schemas/#DensityProperty).
The unit of the `DensityProperty` is `microgram per cubic metre`, just like the PM2.5 property.
The AQI, on the other hand, is just an index based on those values.

**Comment by kgiori** [comment]
Oh I get it. Makes sense to me now -- thanks for the explanation.
