### ISSUE TITLE
Restart of add-on loses Capability selected by user

### ISSUE THREAD

**Issue by kgiori** [tim-hellhake/purpleair-adapter#3]
I think this occurs whenever the Purple Air add-on is restarted. The icon goes back to showing "THING" on the main icon, instead of the value from selecting a "Capability" for the main icon, such as Air Quality, Temp, ...

**Comment by tim-hellhake** [comment]
> I think this occurs whenever the Purple Air add-on is restarted

I tried it a few times, but I could only reproduce it once.
Maybe it's timing related.
There was one strange thing, though.
The package name of the adapter was undefined.
The new update sets it correctly.
I hope this fixes the issue.

**Comment by kgiori** [comment]
I applied this update, which likely restarted the add-on, and the Multi Level Sensor capability is still applied to all the sensors -- seems that your bug fix made this work!
